segmentation_model : 'facebook/sam-vit-base'
detection_model : 'yolov8l'
model : 'kandinsky-community/kandinsky-2-2-decoder-inpaint'
target_width : 2560
target_height : 1472
prompt : 'Product on the table 4k ultrarealistic'
negative_prompt : 'low resolution , bad resolution , Deformation , Weird Artifacts, bad quality,blown up image, high brightness , high saturation '
roi_scale : 0.6
strength : 0.5
guidance_scale : 8
num_inference_steps : 150
output_path : '../outputs'

 