segmentation_model : 'facebook/sam-vit-huge'
detection_model : 'yolov8l'
model : 'kandinsky-community/kandinsky-2-2-decoder-inpaint'
target_width : 1920
target_height : 1080
prompt : 'product in the kitchen used in cooking 4k'
negative_prompt : 'low resolution , bad resolution'
roi_scale : 0.7
strength : 0.2
guidance_scale : 7.0
num_inference_steps : 800
output_path : '../outputs'
 