<<<<<<< HEAD
segmentation_model : 'facebook/sam-vit-base'
detection_model : 'yolov8s'
model : 'kandinsky-community/kandinsky-2-2-decoder-inpaint'
target_width : 2560
target_height : 1472
prompt : 'Product on the table 4k ultrarealistic'
negative_prompt : 'low resolution , bad resolution , Deformation , Weird Artifacts, bad quality,blown up image, high brightness , high saturation '
roi_scale : 0.9
strength : 0.6
guidance_scale : 7
num_inference_steps : 150
output_path : '../outputs'

=======
segmentation_model : 'facebook/sam-vit-large'
detection_model : 'yolov8l'
model : 'kandinsky-community/kandinsky-2-2-decoder-inpaint'
target_width : 1920
target_height : 1080
prompt : 'product is on the kitchen floor , ultrarealistic lighting , commercial, award , winning photography'
negative_prompt : 'low resolution , bad resolution'
roi_scale : 0.5
strength : 0.7
guidance_scale : 7.5
num_inference_steps : 600
output_path : '../outputs'
>>>>>>> a817fb6 (chore: Update .gitignore and add new files for inpainting pipeline)
 