LOGS_DIR = '../logs'
DATA_DIR = '../data'
Project_Name = 'product_placement_api'
entity = 'vikramxd'
image_dir = '../sample_data'
mask_dir = '../masks'
segmentation_model = 'facebook/sam-vit-large'
detection_model = 'yolov8l'
controlnet_adapter_model_name= 'lllyasviel/control_v11p_sd15_inpaint'
controlnet_base_model_name = "runwayml/stable-diffusion-inpainting"
kandinsky_model_name = 'kandinsky-community/kandinsky-2-2-decoder-inpaint'
video_model_name = 'stabilityai/stable-video-diffusion-img2vid-xt'
target_width = 2560
target_height = 1440
roi_scale = 0.6
