LOGS_DIR = '../logs'
Dataset_Name = "AlekseyKorshuk/product-photography-all"
DATA_DIR = '../data'
Project_Name = 'product_placement_diffusers'
entity = 'vikramxd'
image_dir = '../sample_data'
mask_dir = '../masks'
controlnet_adapter_model_name= 'lllyasviel/control_v11p_sd15_inpaint'
controlnet_base_model_name = "runwayml/stable-diffusion-inpainting"
stable_diffusion_inpainting_model_name = "stabilityai/stable-diffusion-2-inpainting"
width = 512
height = 512
