name: Publish Docker Image

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t yourdockerhubusername/imagename:tag .
          docker push yourdockerhubusername/imagename:tag
        env:
          DOCKER_BUILDKIT: 1

      # Optionally, clean up Docker images to save space:
      - name: Clean up
        run: docker image prune -af

