name: Docker Build and Push Serverless

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - functionality: text-to-image
            dockerfile: serverless/text-to-image/Dockerfile
          - functionality: outpainting
            dockerfile: serverless/outpainting/Dockerfile
          - functionality: inpainting
            dockerfile: serverless/inpainting/Dockerfile
          - functionality: image2video
            dockerfile: serverless/image2video/Dockerfile

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ${{ matrix.dockerfile }}
        push: true
        tags: ${{secrets.DOCKER_USERNAME }}/picpilot_${{ matrix.functionality }}:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

  notify:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Check build status
        run: |
          if [ "${{ needs.build-and-push.result }}" == "success" ]; then
            echo "All images built and pushed successfully"
          else
            echo "Some builds failed, check the logs"
            exit 1
          fi