name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Set up Git config
        run: |
          git config user.name "Your Name"
          git config user.email "your-email@example.com"
      - name: Pull from remote
        run: git pull https://VikramSingh178:$HF_TOKEN@huggingface.co/spaces/VikramSingh178/picpilot-server main
      - name: Push to hub
        run: git push https://VikramSingh178:$HF_TOKEN@huggingface.co/spaces/VikramSingh178/picpilot-server main
